{
 "title": "container-etcd",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kube-system\",pod_name=\"etcd-k8s\",name=~\"k8s_etcd_etcd-k8s_kube-system_.+\",}[1m]) * 100"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MiB" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"kube-system\",pod_name=\"etcd-k8s\",name=~\"k8s_etcd_etcd-k8s_kube-system_.+\"}/1024/1024"
    }
   ]
  },
  {
   "title": "disk space usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MiB" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{namespace=\"kube-system\",pod_name=\"etcd-k8s\",name=~\"k8s_etcd_etcd-k8s_kube-system_.+\"}/1024/1024"
    }
   ]
  }
 ]
}