{
 "title": "node-k8s",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_cpu{mode!=\"idle\",mode!=\"iowait\"}[1m])) BY (instance,cpu)) * 100"
    }
   ]
  },
  {
   "title": "memory utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable) by (instance) / sum(node_memory_MemTotal) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "disk space utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_avail{mountpoint=\"/etc/hosts\"}) by (instance,device) / sum(node_filesystem_size{mountpoint=\"/etc/hosts\"}) by (instance,device)) * 100"
    }
   ]
  },
  {
   "title": "network throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "MiB / Sec" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes{device=\"eth0\"}[1m])) by (instance,device) + sum(rate(node_network_transmit_bytes{device=\"eth0\"}[1m])) by (instance,device))/1024/1024"
    }
   ]
  }
 ]
}