{
 "title": "pod-etcd",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"cadvisor\",namespace=\"kube-system\",pod_name=\"etcd-k8s\",container_name!~\".+\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "network throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MiB / Sec" }
   ],
   "targets": [
    {
     "expr": "(rate(container_network_transmit_bytes_total{job=\"cadvisor\",namespace=\"kube-system\",pod_name=\"etcd-k8s\",container_name=\"POD\",interface=\"eth0\"}[1m]) + rate(container_network_receive_bytes_total{job=\"cadvisor\",namespace=\"kube-system\",pod_name=\"etcd-k8s\",container_name=\"POD\",interface=\"eth0\"}[1m])) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "MiB" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor\",namespace=\"kube-system\",pod_name=\"etcd-k8s\",container_name!~\".+\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "disk space usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "MiB" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{job=\"cadvisor\",namespace=\"kube-system\",pod_name=\"etcd-k8s\",container_name=~\".+\",device=\"/dev/vda1\"}) / 1024 / 1024"
    }
   ]
  }
 ]
}