kind: ResourceQuota
apiVersion: v1
metadata:
  name: compute-resources
  namespace: user-x
spec:
  hard:
    pods: "1"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.nvidia.com/gpu: 1
