kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-x
  namespace: user-x
subjects:
- kind: User
  name: user-x
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: user-x
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: user-x
  namespace: user-x
roleRef:
  kind: Role
  name: user-x
  apiGroup: rbac.authorization.k8s.io
