apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: team1
spec:
  hard:
    pods: "1"

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: team2
spec:
  hard:
    pods: "1"

