kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
subjects:
- kind: User
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
